apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-service
spec:
  selector:
    app: kubernetes-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
