name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # HTML Lint
      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Lint HTML files
        run: htmlhint "**/*.html"

      # CSS Lint
      - name: Install Stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Lint CSS files
        run: stylelint "**/*.css"

      # JS Lint
      - name: Install ESLint
        run: npm install -g eslint

      - name: Initialize ESLint config
        run: eslint --init --no-eslintrc || true

      - name: Lint JS files
        run: eslint "**/*.js" || echo "Ignore eslint warnings"

      # Docker Build & Push
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: altjin09/kubernetes_test:latest

      # Kubernetes deployment
      - name: Create Kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kind cluster
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/webapp-deployment

